# Generated by Django 5.2.15 on 2026-06-19 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0004_add_session_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('effect', models.JSONField(help_text='Structured modifier the stat layer can read, e.g. {"stat": "strength", "bonus": 2} or {"damage_mult": 1.1}')),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot', models.CharField(choices=[('WEAPON', 'Weapon'), ('ARMOR', 'Armor'), ('TRINKET', 'Trinket'), ('CONSUMABLE', 'Consumable'), ('MISC', 'Misc')], default='MISC', max_length=20)),
                ('damage_die', models.CharField(blank=True, max_length=20, null=True)),
                ('attack_stat', models.CharField(blank=True, max_length=20, null=True)),
                ('hit_bonus', models.IntegerField(default=0)),
                ('ac_bonus', models.IntegerField(default=0)),
                ('stat_bonuses', models.JSONField(blank=True, default=dict)),
                ('lore', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relics', to='legacy.playerprofile')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relics', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('DIED', 'Died'), ('WON', 'Won'), ('ABANDONED', 'Abandoned')], max_length=20)),
                ('stat_snapshot', models.JSONField(default=dict, help_text='Frozen stat snapshot at session end')),
                ('deeds', models.JSONField(default=list, help_text='List of notable deeds during the run')),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_summaries', to='legacy.playerprofile')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_summary', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='legacy.legacyperk')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_perks', to='legacy.playerprofile')),
            ],
            options={
                'unique_together': {('profile', 'perk')},
            },
        ),
    ]
