# Generated by Django 5.2.15 on 2026-06-18 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0002_message_diceroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_hp', models.IntegerField(default=10)),
                ('current_hp', models.IntegerField(default=10)),
                ('armor_class', models.IntegerField(default=10)),
                ('attack_bonus', models.IntegerField(default=0)),
                ('damage_die', models.CharField(default='1d6', max_length=10)),
                ('status', models.CharField(choices=[('ALIVE', 'Alive'), ('DEAD', 'Dead')], default='ALIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='game.gamesession')),
            ],
        ),
    ]
