[pytest]
DJANGO_SETTINGS_MODULE = ai_dungeon_master.config.settings.development
testpaths = ai_dungeon_master
addopts = --tb=short -q
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')