# Generated by Django 5.2.12 on 2026-04-05 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('world', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEAD', 'Dead')], default='ACTIVE', max_length=20)),
                ('turn_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, help_text='Summary of old events for AI context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='characters.character')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='world.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='world.worldsetting')),
            ],
        ),
    ]
