# Generated by Django 5.2.14 on 2026-06-06 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('game', '0002_message_diceroll'),
        ('world', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-last_played']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='diceroll',
            name='breakdown',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='diceroll',
            name='dc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diceroll',
            name='modifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diceroll',
            name='skill',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='diceroll',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='last_played',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='has_dice_roll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_combat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='raw_response',
            field=models.TextField(blank=True, help_text='Raw JSON or text from AI for debugging'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'status'], name='game_gamese_user_id_4d77eb_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'last_played'], name='game_gamese_user_id_3eb002_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'created_at'], name='game_messag_session_2d2fbb_idx'),
        ),
    ]
