# Generated by Django 5.2.13 on 2026-06-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("prompt_tokens_est", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("rate_limited", "Rate limited (429)"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["provider", "created_at"],
                        name="ai_usagerec_provide_1a0813_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="ai_usagerec_status_425d5c_idx",
                    ),
                ],
            },
        ),
    ]
