# Generated by Django 5.2.12 on 2026-04-05 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(choices=[('HUMAN', 'Human'), ('ELF', 'Elf'), ('DWARF', 'Dwarf'), ('ORC', 'Orc')], default='HUMAN', max_length=20)),
                ('character_class', models.CharField(choices=[('WARRIOR', 'Warrior'), ('WIZARD', 'Wizard'), ('ROGUE', 'Rogue'), ('CLERIC', 'Cleric')], default='WARRIOR', max_length=20)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=10)),
                ('current_hp', models.IntegerField(default=10)),
                ('armor_class', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=30)),
                ('background', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=50)),
                ('damage', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_gold', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='characters.character')),
            ],
        ),
    ]
