# Generated by Django 5.2.14 on 2026-06-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='ac_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='attack_stat',
            field=models.CharField(blank=True, choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='damage_die',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='equipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='hit_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='slot',
            field=models.CharField(choices=[('WEAPON', 'Weapon'), ('ARMOR', 'Armor'), ('TRINKET', 'Trinket'), ('CONSUMABLE', 'Consumable'), ('MISC', 'Misc')], default='MISC', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stat_bonuses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
